# https://github.com/marketplace/actions/install-nix?version=v13
name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --command 'npm install'
    - run: nix-shell --command 'spago -x spago-plugin.dhall build'
    - run: nix-shell --command 'protoc --purescript_out=./test/generated test/*.proto'
    - run: nix-shell --command 'spago -x spago-test.dhall test'
